meta:
  run_name: LoveLace-M-dph
  validate: true
  evaluate: false
  validate_freq: 4
  prompt_validate: false
  tags:
    - improved_dph
    - dph_sweep

model:
  trainable_embeddings: true
  recompute_kv: false

train:
  batch_size: 64
  batch_size_step: 0
  batches_per_epoch: 256
  length_sequence: 2048
  length_cache: 2048
  lr_max: 1.0e-5
  lr_warmup_steps: 2048
  lr_cooldown_tokens: 10000000000
  lr_cooldown_ratio: 0.1

  opt_beta_1: 0.9
  opt_beta_2: 0.95
  opt_weight_decay: 0.1
  opt_decay_init: true
  opt_decay_mask:
    - embedding.weight
    - norm
    - bias

finetune:
  mask_override: train
  mode: dph
  checkpoint: CHANGE_ME
  trainable_backbone: true

dph:
  dph_contrastive: true
  dph_epsilon: 0.0
  dph_weight: 1.0
  dph_penalty: 0.1

  dph_decay_init: false
  dph_weight_decay: 0.1
  dph_lr_multiplier: 10.0
  dph_decay_mask:
    - norm
    - bias

  opt_split_norm: false
