meta:
  tags:
    - improved_pooler

model:
  pooler_config:
    reward_heads:
      - reward_head
    reward_head_bias: true
    embedding_dropout: 0.1

    layer_pooling: weighted_sum
    layer_pooling_norm: post
    layer_pooling_dropout: 0.1

    token_pooling: attn
    token_pooling_norm: post
    token_pooling_config:
      sep_token_id: 50265
      cls_token_id: 50266
      new_token_id: 50118
      pad_token_id: 1
      
      alibi_slope: 8.0
    
    embedding_pooling: null