meta:
  group:
    variant: P-sandwich

model:
  pooler_config:
    token_pooling_config:
      attn_layers:
        - pool
        - ffn
        - cross
        - ffn
        - pool
      
      # norm: both
      # head_gate: false

      n_repeats: 1