meta:
  group:
    variant: 2x4

model:
  pooler_config:
    token_pooling_config:
      attn_layers:
        - pool
        - cross
      
      # norm: both
      # head_gate: false

      n_repeats: 4