meta:
  run_name: Qwen-0.5-dph

train:
  batch_size_step: 4

finetune:
  wrapped_model: Qwen/Qwen1.5-0.5B
  frozen_params:
    - model.layers

model:
  pooler_config:
    layer_select: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24 ]
