meta:
  run_name: LoveLace-M-sft
  validate: true
  validate_freq: 4
  prompt_validate: true
  tags:
    - improved_dph
  validation_batch: 8

model:
  trainable_embeddings: true
  recompute_kv: true

train:
  batch_size: 0
  batch_size_step: 0
  batches_per_epoch: 0
  length_sequence: 2048
  length_cache: 2048
  lr_max: 3.0e-5
  lr_warmup_steps: 0
  lr_cooldown_tokens: 30000000000
  lr_cooldown_ratio: 0.1

  opt_beta_1: 0.9
  opt_beta_2: 0.95
  opt_weight_decay: 0.1
  opt_decay_init: true
  opt_decay_mask:
    - embedding.weight
    - norm
    - bias

finetune:
  mask_override: train
  mode: sft
  checkpoint: lswt_medium_2k4k_100B
  trainable_backbone: true
