finetune:
  sft_mix_name: sft-mix-all
  sft_mix:
    glue/cola: 1.0
    glue/mnli: 1.0
    glue/mrpc: 1.0
    glue/qnli: 1.0
    glue/qqp: 1.0
    glue/rte: 1.0
    glue/sst2: 1.0
    glue/stsb: 1.0
    glue/wnli: 1.0

    mmlu/all: 1.0
    race/middle: 1.0
    race/high: 1.0
    squad/v2: 1.0
    hellaswag/choice: 1.0

    super_glue/copa: 1.0
    hellaswag/no_choice: 1.0

    obqa/main: 1.0
    winogrande/no_choice: 1.0
    arc/challenge: 1.0
    arc/easy: 1.0
    super_glue/boolq: 1.0
    piqa/no_choice: 1.0

    sciq/no_choice: 1.0
    drop/main: 1.0
    gsm8k/main: 1.0
    gsm8k/socratic: 1.0

    alpaca/cleaned: 1.0
    coqa/all: 1.0
    tulu/v2: 1.0
    orca/SlimOrca: 1.0
    ultrachat/200k: 1.0
    baai/Infinity-Instruct: 1.0
    
    cnn_dailymail/3.0.0: 1.0
    tiny/instruct: 1.0
    tiny/summary: 1.0
