finetune:
  dph_mix_name: dph-mix-elbow
  dph_mix_elbow: 160000
  dph_mix:
      glue/cola: 1.0
      glue/mnli: 1.0
      glue/mrpc: 1.0
      glue/qnli: 1.0
      glue/qqp: 1.0
      glue/rte: 1.0
      glue/sst2: 1.0
      glue/stsb: 1.0

      mmlu/all: 1.0
      race/middle: 1.0
      race/high: 1.0
      hellaswag/choice: 1.0
      squad/v2: 1.0
      sciq/no_choice: 1.0

      hellaswag/no_choice: 1.0
      obqa/main: 1.0
      winogrande/no_choice: 1.0
      arc/challenge: 1.0
      arc/easy: 1.0
      super_glue/boolq: 1.0
      piqa/no_choice: 1.0
      
      ultrafeedback/multi-binarized: 1.0
      orca/orca_dpo_pairs: 1.0
      hh/rlhf: 1.0
      OpenHermes/Preferences: 1.0

      glue/wnli: 1.0
      super_glue/copa: 1.0