model:
  pooler_config:
    reward_heads:
      - quality
      - toxicity
      - humor
      - creativity
      - helpfulness
      - correctness
      - coherence
      - complexity
      - verbosity
    reward_head_bias: true

    layer_pooling: weighted_sum
    layer_pooling_norm: both

    token_pooling: ema
    token_pooling_norm: post
    token_pooling_ema_beta: 0.95
    token_pooling_ema_beta_learnable: activation
    token_pooling_gate: true
    token_pooling_gate_bias: false

    token_pooling_rotation: true
    token_pooling_rotation_expansion: 1

    pooler_function: identity

    layer_select: [ 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18 ]
    
    embedding_dropout: 0.1
    layer_dropout: 0.2
    intermediate_dropout: 0.0