model:
  pooler_config:
      reward_heads: [ 'reward_head' ]
      reward_head_bias: true

      layer_pooling: weighted_sum
      layer_pooling_norm: null

      token_pooling: ema
      token_pooling_norm: post
      token_pooling_ema_beta: 0.9
      token_pooling_ema_beta_learnable: activation

      token_pooling_rotation: true

      pooler_function: identity

      layer_select: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18 ]
      
      embedding_dropout: 0.1