finetune:
  sft_mix_name: sft_mix
  sft_mix:
    - [ glue/cola, 1, false ]
    - [ glue/mnli, 1, false ]
    - [ glue/mrpc, 1, false ]
    - [ glue/qnli, 1, false ]
    - [ glue/qqp, 1, false ]
    - [ glue/rte, 1, false ]
    - [ glue/sst2, 1, false ]
    - [ glue/stsb, 1, false ]

    - [ mmlu/all, 1, false ]
    - [ race/middle, 1, false ]
    - [ race/high, 1, false ]
    - [ squad/v2, 1, false ]
    - [ hellaswag/choice, 1, false ]

    - [ hellaswag/no_choice, 1, false ]
    - [ obqa/main, 1, false ]
    - [ winogrande/no_choice, 1, false ]
    - [ arc/challenge, 1, false ]
    - [ arc/easy, 1, false ]
    - [ super_glue/boolq, 1, false ]
    - [ piqa/no_choice, 1, false ]

    - [ super_glue/copa, 1, false ]
    - [ sciq/no_choice, 1, false ]
    - [ drop/main, 1, false ]
    - [ gsm8k/main, 1, false ]
    - [ gsm8k/socratic, 1, false ]

    - [ alpaca/cleaned, 1, true ]
    - [ coqa/all, 1, false ]
    - [ tulu/v2, 5, false ]
    - [ orca/OpenOrca, 5, true ]
    - [ ultrachat/200k, 5, false ]

    - [ cnn_dailymail/3.0.0, 1, false ]
    - [ tiny/instruct, 1, false ]
    - [ tiny/summary, 1, false ]
