finetune:
  sft_mix_name: sft_mix_instruct
  sft_mix:
    - [ drop/main, 1, false ]
    - [ gsm8k/main, 1, false ]

    - [ alpaca/cleaned, 1, true ]
    - [ coqa/all, 1, true ]
    - [ tulu/v2, 5, true ]
    - [ orca/SlimOrca, 5, true ]
    - [ ultrachat/200k, 5, true ]
    - [ baii/Infinity-Instruct, 5, true ]

    - [ cnn_dailymail/3.0.0, 1, false ]
    - [ tiny/instruct, 1, false ]
    - [ tiny/summary, 1, false ]
