meta:
  run_name: LoveLace-M-sft
  validate: true
  validate_freq: 4
  prompt_validate: true
  tags:
    - improved_dph

model:
  trainable_embeddings: true
  recompute_kv: true

train:
  batch_size: 64
  batch_size_step: 0
  batches_per_epoch: 256
  length_sequence: 2048
  length_cache: 2048
  lr_max: 3.0e-5
  lr_warmup_steps: 2000
  lr_cooldown_tokens: 10000000000
  lr_cooldown_ratio: 0.1

  opt_beta_1: 0.9
  opt_beta_2: 0.999
  opt_weight_decay: 0.1
  opt_decay_init: true
  opt_decay_mask:
    - embedding.weight

finetune:
  mask_override: train
  mode: sft
  checkpoint: CHANGE_ME
  trainable_backbone: true
