meta:
  run_name: LoveLace-M-vocab
  validate: true
  validate_freq: 4
  tags:
    - improved_dph

model:
  trainable_embeddings: true
  recompute_kv: false

train:
  batch_size: 64
  batch_size_step: 0
  batches_per_epoch: 256
  length_sequence: 2048
  length_cache: 2048
  lr_max: 6.0e-5
  lr_warmup_steps: 200
  lr_cooldown_tokens: 3000000000
  lr_cooldown_ratio: 0

  opt_weight_decay: 0.1
  opt_decay_init: true
  opt_decay_mask:
    - embedding.weight

finetune:
  mask_override: train
  mode: vocab
  checkpoint: lswt_medium_2k4k_100B
  trainable_backbone: false